services:
  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8315}:8761
    networks:
      - mhws-hs

  cms-postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: db_cms
      HS_POSTGRES_USERNAME: hs
      HS_POSTGRES_PASSWORD: example
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/entrypoint/:/docker-entrypoint-initdb.d/
    networks:
      - mhws-hs

  liquibase:
    image: liquibase/liquibase:4.24-alpine
    depends_on:
      - cms-postgres
    environment:
      LIQUIBASE_COMMAND_USERNAME: hs
      LIQUIBASE_COMMAND_PASSWORD: example
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://cms-postgres:5432/db_cms
    volumes:
      - ./services/liquibase/changelog:/liquibase/changelog
      - ./services/liquibase/liquibase.cms.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update
    networks:
      - mhws-hs

  cms:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${HS_USER_PORT:-8310}:8763
    environment:
      HS_CMS_EUREKA_URI: http://eureka:8761/eureka
      HS_CMS_DATASOURCE_HOST: cms-postgres
      HS_CMS_DATASOURCE_PORT: 5432
      HS_CMS_DATASOURCE_DATABASE: db_cms
      HS_CMS_DATASOURCE_USERNAME: hs
      HS_CMS_DATASOURCE_PASSWORD: example
    networks:
      - mhws-hs

volumes:
  postgres-data:

networks:
  mhws-hs:
    external: true
